### ISSUE TITLE
How do you use the `-i` parameter?

### ISSUE THREAD

**Issue by TheTechRobo** [Nold360/docker-grab-site#2]
The `-i <FILE>` parameter means "read URLs from <FILE>". How would that work, if grab-site is containerized? How do I pass in <FILE>?

**Comment by exurd** [comment]
Place the text file in the data folder. You can then use the parameter like this: `-i /data/file.txt`

**Comment by TheTechRobo** [comment]
Yeah, I did end up doing that. Worked fine.
