### ISSUE TITLE
Building Dockerfile after commit 7fb5ba5: No matching distribution found for google-re2>=1.0.6

### ISSUE THREAD

**Issue by exurd** [Nold360/docker-grab-site#6]
grab-site's setup.py replaced the `fb-re2` package in commit [7fb5ba5](https://github.com/ArchiveTeam/grab-site/commit/7fb5ba51ecceb8b12c38ecbf1dd08b4c3b99f3f5). Every version of `google-re2` requires Python 3.8 or above, which causes the build to fail. The previous commit [8016234](https://github.com/ArchiveTeam/grab-site/commit/8016234f3b0cac0e275137c977d6d177dbc34f2a) builds correctly.

Failed build log:
[docker_build_log.log](https://github.com/user-attachments/files/16741215/docker_build_log.log)

**Comment by Nold360** [comment]
Should be fixed with 42538c61303c698963969930d6bb90b2b1e0e100
